### ISSUE TITLE
Problem with first time admin account creation. Context: Failed to connect to the database

### ISSUE THREAD

**Issue by SC-Serv** [klutchell/balena-nextcloud#63]
Flashed this device twice and got the same thing, used to have this happen before but seemed to have a been a hit or a miss back when nextcloud was on version 23 I think.
"Error while trying to create admin user: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [1130] Host '172.17.0.4' is not allowed to connect to this MariaDB server"

**Comment by SC-Serv** [comment]
The logs from power on 
nextcloud  crond: crond (busybox 1.35.0) started, log level 0
 nextcloud  crond: user:www-data entry:*/5 * * * * php -f /var/www/html/cron.php
 nextcloud  100001000010000100001000010000100001000010000100001000010000
 nextcloud  111111111111111111111111
 nextcloud  11111111111111111111111111111111
 nextcloud  111111111111
 nextcloud  1111111
 nextcloud  2022-09-20 01:50:17,715 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
 nextcloud  2022-09-20 01:50:17,715 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
 nextcloud  2022-09-20 01:50:17,717 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
 nextcloud  2022-09-20 01:50:17,717 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
 nextcloud  Nextcloud is not installed - only a limited number of commands are available
 nextcloud  
 nextcloud                                                                     
 nextcloud    There are no commands defined in the "config:system" namespace.  
 nextcloud                                                                     
 nextcloud  
 nextcloud  Nextcloud is not installed - only a limited number of commands are available
 nextcloud  
 nextcloud                                                                     
 nextcloud    There are no commands defined in the "config:system" namespace.  
 nextcloud                                                                     
 nextcloud  
 nextcloud  parse error: Invalid numeric literal at line 66, column 23
 nextcloud  [20-Sep-2022 01:50:23] NOTICE: fpm is running, pid 33
 nextcloud  [20-Sep-2022 01:50:23] NOTICE: ready to handle connections
 redis  1:M 20 Sep 2022 01:45:47.144 * 100 changes in 300 seconds. Saving...
 redis  1:M 20 Sep 2022 01:45:47.150 * Background saving started by pid 16
 redis  16:C 20 Sep 2022 01:45:47.178 * DB saved on disk
 redis  16:C 20 Sep 2022 01:45:47.181 * RDB: 0 MB of memory used by copy-on-write
 redis  1:M 20 Sep 2022 01:45:47.251 * Background saving terminated with success
 redis  1:signal-handler (1663638541) Received SIGTERM scheduling shutdown...
 redis  1:M 20 Sep 2022 01:49:01.215 # User requested shutdown...
 redis  1:M 20 Sep 2022 01:49:01.215 * Saving the final RDB snapshot before exiting.
 redis  1:M 20 Sep 2022 01:49:01.247 * DB saved on disk
 redis  1:M 20 Sep 2022 01:49:01.247 # Redis is now ready to exit, bye bye...
 redis  1:C 20 Sep 2022 01:50:05.018 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
 redis  1:C 20 Sep 2022 01:50:05.018 # Redis version=6.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
 redis  1:C 20 Sep 2022 01:50:05.018 # Configuration loaded
 redis  1:M 20 Sep 2022 01:50:05.024 * monotonic clock: POSIX clock_gettime
 redis  1:M 20 Sep 2022 01:50:05.044 # A key '__redis__compare_helper' was added to Lua globals which is not on the globals allow list nor listed on the deny list.
 redis                  _._                                                  
 redis             _.-``__ ''-._                                             
 redis        _.-``    `.  `_.  ''-._           Redis 6.2.7 (00000000/0) 64 bit
 redis    .-`` .-```.  ```\/    _.,_ ''-._                                  
 redis   (    '      ,       .-`  | `,    )     Running in standalone mode
 redis   |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 redis   |    `-._   `._    /     _.-'    |     PID: 1
 redis    `-._    `-._  `-./  _.-'    _.-'                                   
 redis   |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 redis   |    `-._`-._        _.-'_.-'    |           https://redis.io       
 redis    `-._    `-._`-.__.-'_.-'    _.-'                                   
 redis   |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 redis   |    `-._`-._        _.-'_.-'    |                                  
 redis    `-._    `-._`-.__.-'_.-'    _.-'                                   
 redis        `-._    `-.__.-'    _.-'                                       
 redis            `-._        _.-'                                           
 redis                `-.__.-'                                               
 redis  
 redis  1:M 20 Sep 2022 01:50:05.047 # Server initialized
 redis  1:M 20 Sep 2022 01:50:05.086 * Loading RDB produced by version 6.2.7
 redis  1:M 20 Sep 2022 01:50:05.086 * RDB age 64 seconds
 redis  1:M 20 Sep 2022 01:50:05.086 * RDB memory usage when created 0.81 Mb
 redis  1:M 20 Sep 2022 01:50:05.087 # Done loading RDB, keys loaded: 4, keys expired: 0.
 redis  1:M 20 Sep 2022 01:50:05.087 * DB loaded from disk: 0.027 seconds
 redis  1:M 20 Sep 2022 01:50:05.087 * Ready to accept connections
 mariadb  2022-09-20  1:45:47 12 [Warning] Aborted connection 12 to db: 'unconnected' user: 'unauthenticated' host: '172.17.0.4' (This connection closed normally without authentication)
 mariadb  2022-09-20  1:49:01 0 [Note] /usr/bin/mysqld (initiated by: unknown): Normal shutdown
 mariadb  2022-09-20  1:49:01 0 [Note] InnoDB: Starting shutdown...
 mariadb  2022-09-20  1:49:01 0 [Note] InnoDB: FTS optimize thread exiting.
 mariadb  2022-09-20  1:49:01 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
 mariadb  2022-09-20  1:49:01 0 [Note] InnoDB: Buffer pool(s) dump completed at 220920  1:49:01
 mariadb  2022-09-20  1:49:01 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
 mariadb  2022-09-20  1:49:01 0 [Note] InnoDB: Shutdown completed; log sequence number 42353; transaction id 15
 mariadb  2022-09-20  1:49:01 0 [Note] /usr/bin/mysqld: Shutdown complete
 mariadb  
 mariadb  [i] mysqld already present, skipping creation
 mariadb  [i] MySQL directory already present, skipping creation
 mariadb  2022-09-20  1:50:05 0 [Note] /usr/bin/mysqld (server 10.6.8-MariaDB) starting as process 1 ...
 mariadb  2022-09-20  1:50:07 0 [Warning] You need to use --log-bin to make --binlog-format work.
 mariadb  2022-09-20  1:50:08 0 [Note] InnoDB: Compressed tables use zlib 1.2.12
 mariadb  2022-09-20  1:50:08 0 [Note] InnoDB: Number of pools: 1
 mariadb  2022-09-20  1:50:08 0 [Note] InnoDB: Using ARMv8 crc32 instructions
 mariadb  2022-09-20  1:50:08 0 [Note] mysqld: O_TMPFILE is not supported on /var/tmp (disabling future attempts)
 mariadb  2022-09-20  1:50:08 0 [Note] InnoDB: Using Linux native AIO
 mariadb  2022-09-20  1:50:08 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
Warning: Suppressed 14 message(s) due to slow reading
 nextcloud  crond: user:www-data entry:*/5 * * * * php -f /var/www/html/cron.php
 nextcloud  100001000010000100001000010000100001000010000100001000010000
 nextcloud  111111111111111111111111
 nextcloud  11111111111111111111111111111111
 nextcloud  111111111111
 nextcloud  1111111
 nextcloud  crond: wakeup dt=44
 nextcloud  crond: file www-data:
 nextcloud  crond:  line php -f /var/www/html/cron.php
 nextcloud  172.17.0.4 -  20/Sep/2022:01:51:22 +0000 "GET /index.php" 200
 nginx  192.168.1.78 - - [20/Sep/2022:01:51:23 +0000] "GET /index.php/csrftoken HTTP/1.1" 200 1536 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.42" "-"
 nextcloud  crond: wakeup dt=60
 nextcloud  crond: file www-data:
 nextcloud  crond:  line php -f /var/www/html/cron.php
 nextcloud  crond: wakeup dt=60
 nextcloud  crond: file www-data:
 nextcloud  crond:  line php -f /var/www/html/cron.php
 nextcloud  172.17.0.4 -  20/Sep/2022:01:53:29 +0000 "GET /index.php" 200
 nginx  192.168.1.78 - - [20/Sep/2022:01:53:29 +0000] "GET / HTTP/1.1" 200 1533 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.100" "-"
 nextcloud  crond: wakeup dt=60
 nextcloud  crond: file www-data:
 nextcloud  crond:  line php -f /var/www/html/cron.php
 mariadb  2022-09-20  1:54:02 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.17.0.5' (This connection closed normally without authentication)
 nextcloud  172.17.0.4 -  20/Sep/2022:01:54:01 +0000 "POST /index.php" 200
 nginx  192.168.1.78 - - [20/Sep/2022:01:54:02 +0000] "POST /index.php HTTP/1.1" 200 2470 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.100" "-"
 nextcloud  crond: wakeup dt=60
 nextcloud  crond: file www-data:
 nextcloud  crond:  line php -f /var/www/html/cron.php
 nextcloud  crond:  job: 0 php -f /var/www/html/cron.php
 nextcloud  crond: USER www-data pid  59 cmd php -f /var/www/html/cron.php
 nextcloud  crond: child running /bin/ash
 nextcloud  Exception: Not installed in /var/www/html/lib/base.php:282
 nextcloud  Stack trace:
 nextcloud  #0 /var/www/html/lib/base.php(670): OC::checkInstalled(Object(OC\SystemConfig))
 nextcloud  #1 /var/www/html/lib/base.php(1111): OC::init()
 nextcloud  #2 /var/www/html/cron.php(43): require_once('/var/www/html/l...')
 nextcloud  #3 {main}
 nextcloud  crond: wakeup dt=10
 nextcloud  crond: wakeup dt=50
 nextcloud  crond: file www-data:
 nextcloud  crond:  line php -f /var/www/html/cron.php

**Comment by klutchell** [comment]
I've seen this happens when mariadb takes a long time to initialize the default database and restart. so Nextcloud can't find an existing database. Sometimes mariadb never gets this far and I could never figure out why? There are a number of GitHub issues around this.

There are a couple workarounds. You could try purging all data from the volumes via the balena dashboard and give mariadb several minutes to get set up before running the Nextcloud wizard (watch the mariadb logs for progress).

You could also log into the mariadb service and create the database manually with the credentials from the [compose file](https://github.com/klutchell/balena-nextcloud/blob/main/docker-compose.yml#L42-L44).

**Comment by SC-Serv** [comment]
After yet another flash and fail of the same reason. I used the purge method in Balena dashboard and it worked. I'm theorizing it to be a timing issue. More specifically when the Balena OS does first time setup and all the modules start that they don't start correctly. I've notice that when first time start happens the modules download and start while others are downloading still. Purging ends up having them all start at once. It could even be the modules are trying to talk to each other and error out a time out cause the other dependencies don't exist yet.

**Comment by klutchell** [comment]
A race condition definitely sounds likely, but I'm not sure the best to work around it except add an entrypoint script to the Nextcloud container to make sure mariadb has finished setting up?

Not sure why Nextcloud starting before mariadb would cause an issue though, unless you tried to run the setup wizard before the DB was created?

**Comment by SC-Serv** [comment]
I'm not sure, but I always let them sit after first time start for 5-7 minutes and always ends up like that. When I first worked with Nextcloud on Pi (and Nextcloud in general on version 23 or since last year) it didn't do it all the time sometimes worked right off the bat. 

If it works after a purge and is by definition factory reset then it has to be either timing issue or some sort of interference from other setups or something. If a purge is a factory reset then the modules are in fact coded right but something messes them up during first boot when the Balena OS starts and then fetching the modules then starting them.

**Comment by klutchell** [comment]
> If it works after a purge and is by definition factory reset then it has to be either timing issue or some sort of interference from other setups or something. If a purge is a factory reset then the modules are in fact coded right but something messes them up during first boot when the Balena OS starts and then fetching the modules then starting them.

A purge via the balena dashboard will stop all services, delete all volumes, and start all services. I suspect there is a condition on first run that causes mariadb to not create the default database. I'm not convinced that the other services are related at all.

> I am also experiencing a new problem, I used to be able to connect to the device via http://nextcloud.local/ (back in v23) but now I cant anymore and can only access it through the IP address. After a purge the config.php for nextcloud in trusted domains is the IP Address and the 'overwrite.cli.url' with the IP. After a reboot of the device it goes to nextcloud.local and the *.balena.com for the trusted but the cli doesnt change.

Can you open a new issue for this so we don't confuse the matter?
